`use buildinfo` in `read_params` of the dice patch (#192)
This PR fixes a bug where the dice patch compilation fails due to
`write_gitinfo`. The compilation error reads "undefined reference to
`write_gitinfo_`". Importing `buildinfo` and passing the argument fixed
the issue. This might have to fixed for other `read_params` files as
well.